brokerClusterName=SafeGuardCluster
brokerName=safeguard-broker-a
brokerId=0
namesrvAddr=rocketmq-namesrv:9876
brokerIP1=rocketmq-broker
listenPort=10911
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true
flushDiskType=SYNC_FLUSH
